name: logseq
base: core22
adopt-info: logseq
summary: Logseq is a privacy-first, open-source knowledge base.
description: |
  Logseq is a privacy-first, open-source knowledge base that works on top of local plain-text Markdown and Org-mode files. Use it to write, organize and share your thoughts, keep your to-do list, and build your own digital garden.

grade: stable
confinement: strict

parts:
  logseq:
    plugin: nil
    source: https://github.com/logseq/logseq.git
    source-depth: 1
    source-tag: '0.10.1'
    build-packages:
      - curl
      - default-jdk
      - zip
    stage-packages:
      - libnss3
      - libnspr4

    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags)

      set -x

      # Install node
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

      # Install clojure at required version
      curl -fsSL https://download.clojure.org/install/linux-install-1.10.1.763.sh | bash -

    override-build: |
      craftctl default

      set -x

      # workaround for remote-build on launchpad
      # https://bugs.launchpad.net/bugs/1886861
      http_proxy=${http_proxy:-""}
      https_proxy=${https_proxy:-""}
      if [ -n "$http_proxy" ]; then

        # Yarn / Npm
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"

        host=$(echo "$http_proxy" | grep -oP '(?<=//)[^:/]+')
        port=$(echo "$http_proxy" | grep -oP '(?<=:)[0-9]+')

        # Clojure / JGit
        export JAVA_TOOL_OPTIONS=" -Dhttps.proxyHost=${host} -Dhttps.proxyPort=${port}"

        # Maven
        mkdir -p $HOME/.m2
        cat > $HOME/.m2/settings.xml <<EOF
        <settings>
          <proxies>
            <proxy>
              <id>remote-build-proxy</id>
                <active>true</active>
                <protocol>http</protocol>
                <host>${host}</host>
                <port>${port}</port>
            </proxy>
          </proxies>
        </settings>
      EOF

        # TODO not working yet
        npm config set proxy ${http_proxy}
        npm config set https-proxy ${https_proxy}

      fi

      npm install --global yarn
      yarn install

      yarn release-electron &&\
      mv ./static/out/Logseq-linux-* $SNAPCRAFT_PART_INSTALL/app &&\
      chmod 755 $SNAPCRAFT_PART_INSTALL/app

apps:
  logseq:
    command: app/Logseq --no-sandbox
    extensions:
      - gnome
    plugs:
      - network
      - shmem
      - home
      - etc-gitconfig
      - gitconfig
      - ssh-keys
      - audio-playback

plugs:
  shmem:
    interface: shared-memory
    private: true
  etc-gitconfig:
    interface: system-files
    read:
    - /etc/gitconfig
  gitconfig:
    interface: personal-files
    read:
    - $HOME/.gitconfig
    - $HOME/.config/git/config
