name: logseq
base: core22
adopt-info: logseq
summary: Logseq is a privacy-first, open-source knowledge base.
description: |
  Logseq is a privacy-first, open-source knowledge base that works on top of local plain-text Markdown and Org-mode files. Use it to write, organize and share your thoughts, keep your to-do list, and build your own digital garden.

grade: stable
confinement: strict

parts:
  logseq:
    plugin: nil
    source: https://github.com/logseq/logseq.git
    source-depth: 1
    source-tag: 0.9.14
    build-packages:
      - curl
      - default-jdk
      - zip
    stage-packages:
      - libnss3
      - libnspr4

    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags)

      set -x

      # Install node
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

      # Install clojure at required version
      curl -fsSL https://download.clojure.org/install/linux-install-1.10.1.763.sh | bash -

    override-build: |
      craftctl default

      set -x

      npm install --global yarn
      yarn install

      yarn release-electron &&\
      mv ./static/out/Logseq-linux-* $SNAPCRAFT_PART_INSTALL/app &&\
      chmod 755 $SNAPCRAFT_PART_INSTALL/app

apps:
  logseq:
    command: app/Logseq --no-sandbox
    extensions:
      - gnome
    plugs:
      - network
      - shmem
      - home

plugs:
  shmem:
    interface: shared-memory
    private: true
