name: Push new tag update to stable branch

on:
  schedule:
    # Daily for now
    - cron: '9 7 * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  update-snapcraft-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Update snapcraft.yaml
        uses: ubuntu/desktop-snaps@12a322bc9b39889b93b71ffa2a1a1b2f0932cff5 # stable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          yaml-path: snap/snapcraft.yaml

      - name: Update legacy (og) snapcraft.yaml
        uses: ubuntu/desktop-snaps@12a322bc9b39889b93b71ffa2a1a1b2f0932cff5 # stable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          yaml-path: snap-og/snap/snapcraft.yaml
