name: Push snap to snapstore edge channel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]

    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: build

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
