name: Push snap to snapstore edge channel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            id: build_amd64
          - runner: ubuntu-24.04-arm
            id: build_arm64

    runs-on: "${{ matrix.runner }}"

    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: ${{ matrix.id }}

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.${{ matrix.id }}.outputs.snap }}
          release: edge
