name: Test snap can be built

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]

    runs-on: "${{ matrix.runner }}"
    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: build

      - uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: 'false'
          plugs: ./plug-declaration.json
