name: Test snap can be built on x86_64

on:
  pull_request:
    branches: [ main ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: build_amd64

      - uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build_amd64.outputs.snap }}
          isClassic: 'false'
          plugs: ./plug-declaration.json

  build-arm64:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: build_arm64

      - uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build_arm64.outputs.snap }}
          isClassic: 'false'
          plugs: ./plug-declaration.json
