name: Test snap can be built

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64

    runs-on: "${{ matrix.runner }}"

    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: build_${{ matrix.arch }}

      - uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build_${{ matrix.arch }}.outputs.snap }}
          isClassic: 'false'
          plugs: ./plug-declaration.json
